-- Create users table
CREATE TABLE IF NOT EXISTS users (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    created_at timestamp(6),
    email varchar(255) NOT NULL UNIQUE,
    name varchar(255) NOT NULL,
    PRIMARY KEY (id)
);